# consistent spacing
newline_style = "Unix"
tab_spaces = 2
hard_tabs = true
#use_small_heuristics = "Max"
# imports
imports_granularity = "Crate"
# misc
chain_width = 60
binop_separator = "Back"
match_arm_leading_pipes = "Preserve"
trailing_comma = "Vertical"
match_block_trailing_comma = true
trailing_semicolon = false
use_field_init_shorthand = true
# comment
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
